---

- src: https://github.com/OULibraries/ansible-role-apache2
  version: v2016-10-17.0
  name: OULibraries.apache2

- src: https://github.com/OULibraries/ansible-role-cas
  version: master
  name: OULibraries.cas

- src: https://github.com/OULibraries/ansible-role-celery-worker
  version: master
  name: OULibraries.celery-worker

- src: https://github.com/OULibraries/ansible-role-centos7
  version: v2017-04-28.0
  name: OULibraries.centos7

- src: https://github.com/OULibraries/ansible-role-d7
  version: v2017-04-28.0
  name: OULibraries.d7

- src: https://github.com/OULibraries/ansible-role-java
  version: master
  name: OULibraries.java

- src: https://github.com/OULibraries/ansible-role-mariadb
  version: v2016-09-26.0
  name: OULibraries.mariadb

- src: https://github.com/OULibraries/ansible-role-nginx
  version: v2017-03-02.0
  name: OULibraries.nginx

- src: https://github.com/OULibraries/ansible-role-ngrok
  version: v2017-01-26.0
  name: OULibraries.ngrok

- src: https://github.com/OULibraries/ansible-role-ojs
  version: master
  name: OULibraries.ojs

- src: https://github.com/OULibraries/ansible-role-postfix-mta
  version: v2016-10-17.0
  name: OULibraries.postfix-mta

- src: https://github.com/OULibraries/ansible-role-users
  version: v2016-11-14.0
  name: OULibraries.users

- src: https://github.com/OULibraries/ansible-role-solr
  version: oulib
  name: geerlingguy.solr

- src: https://github.com/OULibraries/ansible-role-solr-onesearch
  version: master
  name: OULibraries.solr-onesearch

- src: https://github.com/OULibraries/ansible-role-sclphp
  version: master
  name: OULibraries.sclphp

- src: https://github.com/OULibraries/ansible-role-searchgateway
  version: master
  name: OULibraries.searchgateway

- src: https://github.com/OULibraries/ansible-role-fcrepo3
  name: OULibraries.fcrepo3

- src: https://github.com/OULibraries/ansible-role-d7-islandora
  name: OULibraries.d7-islandora
