---
- hosts: vagrant
  vars_files:
    - my-vars.yml
  roles:
    - OULibraries.centos7
  pre_tasks:
    - include: pretasks.yml
      sudo: yes

- hosts: cas.vagrant.dev
  sudo: yes
  vars_files:
    - my-vars.yml
  roles:
    - OULibraries.cas

- hosts: d7.vagrant.dev
  sudo: yes
  vars_files:
    - my-vars.yml
  pre_tasks:
    - name: /srv is a directory
      file: path=/srv state=directory mode=0755 force=yes

    - name: Check preconditions for running playbook. 
      assert:
        that:
          - mariadb_root_pass is defined
  roles:
    - OULibraries.mariadb
    - OULibraries.apache2
    - OULibraries.d7
  tasks:
    - name: Add apache user to vagrant group
      user:
        name: apache
        append: yes
        groups: vagrant
    - name: Add vagrant user to apache group
      user:
        name: vagrant
        append: yes
        groups: apache

- hosts: nginx.vagrant.dev
  sudo: yes
  vars_files:
    - my-vars.yml
  roles:
    - OULibraries.nginx

- hosts: vagrant
  vars_files:
    - my-vars.yml
  roles:
    - OULibraries.users
