---
# Solr config
# See https://github.com/geerlingguy/ansible-role-solr
solr_version: "4.10.4"    
solr_install_dir: "/opt/"
solr_install_path: "/opt/solr"
solr_home: "/var/solr"
solr_port: "8983"
solr_xmx: "512M"
solr_cores:
  - collection1
solr_log_file_path: "/var/log/solr.log"
# listen on all interfaces
solr_host: "0.0.0.0"

onesearch_solr_user: "solr"
onesearch_solr_pass: "solr"

nginx_sites:
  - name: solr.vagrant.localdomain
    cert_name: "{{ my_httpd_dn_suffix }}"
    robots: disallow
    upstreams:
      - name: local-solr-jetty
        secure: false
        servers:
          - 127.0.0.1:8983
        locations:
          - location_match: /
