---
- name: Copy hosts file
  copy:
    src: /vagrant/hosts
    dest: /etc/hosts
- name: Enable selinux for testing
  selinux:
    state: enforcing
    policy: targeted
  when: environment_name != "vagrant"
- name: Disable selinux for vagrant dev
  selinux:
    state: permissive
    policy: targeted
  when: environment_name == "vagrant"
