---
# Style of environment to build: vagrant, test or prod
environment_name: "webdev"

# APC?
apc_enabled: "0"

# Drupal site email
drupal_sitemail: "lib-noreply@ou.edu"

# Your email address -- for let's encrypt?
email: "{{ my_email }}"

# Local APC credentials
apc_username: "apcuser"
apc_password: "apcpass123"

# Passing the local domain on to apache
httpd_dn_suffix: "d7.{{ my_httpd_dn_suffix }}"

# root db password
mariadb_root_pass: 'root'

# Email config
smtp_host: smtp.office365.com
smtp_port: 587
smtp_domain: ou.edu
smtp_start_tls: "YES"
smtp_from_line_override: "YES"
smtp_authuser: "{{my_smtp_authuser }}"
smtp_authpassword: "{{ my_smtp_authpassword }}"
sendmail_users:
  - apache
  - root

# Drupal related settings
d7_memory_limit: "256M"
d7_upload_max_filesize: "64M"
d7_post_max_size: "70M"
d7_date_timezone: "America/Chicago"

# Control of PHP session expiration
d7_session_cookie_lifetime: "900"
d7_session_gc_probability: "1"
d7_session_gc_divisor: "1"

# D7 CAS Host
d7_cas: "login.opstest.lib.ou.edu"
