---
# Configure a common baseline for all hosts
- hosts: vagrant
  become: true
  roles:
    - role: OULibraries.centos7
      tags: centos7
  pre_tasks:
    - include: pretasks.yml
      tags: pretasks

 # Build a stand-alone dspace box
- hosts: dspace.vagrant.localdomain
  sudo: yes
  roles:
    - role: OULibraries.postgresql-server
      tags: postgresql-server
    - role: OULibraries.dspace6
      tags: dspace6

# Got back and configure interactive users and devel settings for all hosts
- hosts: vagrant
  become: true
  roles:
    - role: OULibraries.users
      tags: users
