---
# Style of environment to build: vagrant, test or prod
environment_name: "vagrant"

# APC?
apc_enabled: "0"

# Drupal site email
drupal_sitemail: "lib-noreply@ou.edu"

# Your email address -- for let's encrypt?
email: "{{ my_email }}"

# Local APC credentials
apc_username: "apcuser"
apc_password: "apcpass123"

# Passing the local domain on to apache
httpd_dn_suffix: "{{ my_httpd_dn_suffix }}"

# root db password
mariadb_root_pass: 'root'

# Email config
smtp_host: smtp.office365.com
smtp_port: 587
smtp_domain: ou.edu
smtp_start_tls: "YES"
smtp_from_line_override: "YES"
smtp_authuser: "{{my_smtp_authuser }}"
smtp_authpassword: "{{ my_smtp_authpassword }}"
sendmail_users:
  - apache
  - root

# Your ngrok token
ngrok_authtoken: "{{my_ngrok_authtoken }}"

# Configuration for tunnels.
# Note that because proto == tls, traffic is encrypted end-to-end, rather than cleartext. This is good.
# DO NOT PASS SENSITIVE DATA OVER CLEARTEXT TUNNELS.
tunnels:
  - name: '*'
    dn_suffix: '{{ my_httpd_dn_suffix }}'
    port: '443'
    proto: 'tls'
