---
# The configuration below would get you a server ready to run
# d7_init.sh /srv/drupal-dev1 and d7_init.sh /srv/drupal-dev2

# This example forwards:
# https://drupal-dev1.drupal.vm.test on the vagrant host to https://drupal-dev1.ngrok.io and
# https://drupal-dev2.drupal.vm.test on the vagrant host to https://drupal-dev2.ngrok.io


# Style of environment to build: vagrant, test or prod
environment_name: "webtest"

# Drupal site email
drupal_sitemail: "lib-noreply@ou.edu"

# APC?
apc_enabled: "0"

# Developer ID and Auth

# Your email address
email: "{{ my_email }}"
# Your ngrok token
ngrok_authtoken: "{{my_ngrok_token }}"

# Local APC credentials
apc_username: "apcuser"
apc_password: "apcpass123"

# Configuration for tunnels.
# Note that because proto == tls, traffic is encrypted end-to-end, rather than cleartext. This is good.
# DO NOT PASS SENSITIVE DATA OVER CLEARTEXT TUNNELS.
tunnels:
  - name: 'repository'
    dn_suffix: 'lo5an.lib.ngrok.io'
    port: '443'
    proto: 'tls'

# Local credentials
# additional shell accounts
users:
  - name: 'libacct'
    groups: 'wheel'
    pubkey: 'ssh-rsa AAAAB3NzaC1yc2EAAAABJQAAAQEAtkaGGkonm3HJmRoupKgM0A04uZu3aPhFyWmyMWCHTk1TtDskTgO0krOgUKuxAB2G/d39Xz6oISL9+dQdZt5aEJK7WoHpkK8l8xXfrIJ8OiWuJ+IRygjjLsib8tVTRsEIvMrQUtnhGzVNM7lQNXaEviGmR+ZunH68fv/QpomR5qW/veLFsR0KQLnd8yoG2+Tm8EdYouDcUPTS1nr9XdPSWGcsvpDq48JdxSmtXXC/8NHfdhpmCMmoC/IXbFl7typeLd9gt7EFvqOLWEbysEF3hD6hMAV3MEWaDnhf25n2cUgdAvdk086REgg2bXx1dBdeSi+wq5MadfP80UuPuaN2lw== libacct@ou.edu'
  - name: 'lmc'
    groups: 'wheel'
    pubkey: 'ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQCygwAuRh3TboS0a6U5F3Mr2ug05PsA7rGHDIuPAFZav6lMpAVcU9YV8/XAULnm+PgqqfhFlUNPcJ4vYJPFNFaarDICPsGK464wpPSRsrV9GFwBeYXCljgDfsT8cUkkdTMRM7KlfRmcVmrNjGFF6lQ/CFosMuHDQJ9bdpVGR1n+L9F3UJp3dHIy/anoPrmZkOLjAzH2LtDNIqNHQtkOQthSwdJ5RA+6n4yypTzYJbynqY/fAo783UkQ+dmpVWDAlSyV8O6xQ+6p1YwcC9ge/1tZ1C8to4JRVYAA2XK1L92MF/x/2r3YTMip41b8VRkYq0GSNh36DVVTypaWqeG5dph+/MQ1xRGQnGGJDqVI5SPaotpSgr4+mU2afCrh+8ENis8NZt+bCC/0vEwxmbk/FcxMxC4M1d6Tp9CeeAqvpKSETyn+Pmuw10faToZqFVH9oULH3m48ccC1k3PCpdcoufCgfeAcvRWSV60Y1WXp1kPwSAnGLGHc1ZzcqHfhvn3a2LmE4SF/EFMQdT6pMOO/ZElwhBhsG1Uio36wYn/E7S9Sr7l+2boC7m146vGigP++D2NbYSfYi6DhMrtsLpRhQkM5CBUYc9LaiROGtoWX3cX8YDYzVOMH0WQ2SXgr38Fis/Zd5FUu9Gwx+pbzRfn9Kf2fd2s3v1pUbkRC5T2mggStcw== lmc@ou.edu'

ssh_brokers:
  - alias: 'broker.prod.ltp.ec2.external'
    ip: '52.7.166.104'
    dn_suffix: 'ec2.internal'
  - alias: 'broker.prod.nor.external'
    ip: '129.15.14.252'
    dn_suffix: 'nor.internal'
    
# root db password
mariadb_root_pass: 'root'

# Passing the local domain on to apache
httpd_dn_suffix: "lo5an.lib.ngrok.io"

# Email config

smtp_host: smtp.office365.com
smtp_port: 587
smtp_domain: ou.edu
smtp_start_tls: "YES"
smtp_from_line_override: "YES"
smtp_authuser: "{{my_smtp_authuser }}"
smtp_authpassword: "{{ my_smtp_authpassword }}"
sendmail_users:
  - apache
  - root
  - lmc






solr_version: "4.10.4"    
solr_install_dir: "/opt/"
solr_install_path: "/opt/solr"

solr_home: "/var/solr"

solr_port: "8983"

solr_xmx: "512M"

solr_cores:
  - collection1

solr_log_file_path: "/var/log/solr.log"

solr_host: "0.0.0.0"
