---
- hosts: vagrant
  sudo: yes
  roles:
    - OULibraries.centos7
  pre_tasks:
    - include: selinux.yml
  post_tasks:
    - include: ipv6.yml


    

- hosts: d7.vagrant.localdomain
  sudo: yes
    
  pre_tasks:
    - name: /srv is a directory
      file: path=/srv state=directory mode=0755 force=yes

    - name: Check preconditions for running playbook.
      assert:
        that:
          - mariadb_root_pass is defined
  roles:
    - role: OULibraries.mariadb
      tags: mariadb
    - role: OULibraries.apache2
      tags: apache2
    - role: OULibraries.d7
      tags: d7
    - role: OULibraries.ngrok
      tags: ngrok

  post_tasks:
    - name: Make sure securepath works
      lineinfile:
        dest: /etc/sudoers
        regexp: '^Defaults    secure_path = .*$'
        line: 'Defaults    secure_path = /sbin:/bin:/usr/sbin:/usr/bin:/opt/php/bin/'
        validate: 'visudo -cf %s'

- hosts: solr.vagrant.localdomain
  sudo: yes
  pre_tasks:
    - name: /srv is a directory
      file: path=/srv state=directory mode=0755 force=yes
  roles:
    - OULibraries.java
    - geerlingguy.solr
  post_tasks:
    - name: Make sure securepath works
      lineinfile:
        dest: /etc/sudoers
        regexp: '^Defaults    secure_path = .*$'
        line: 'Defaults    secure_path = /sbin:/bin:/usr/sbin:/usr/bin:/opt/php/bin/'
        validate: 'visudo -cf %s'

- hosts: vagrant
  roles:
    - role: OULibraries.users
      tags: users
