---
# Style of environment to build: vagrant, test or prod
environment_name: "vagrant"

# Local credentials
# additional shell accounts
users:
  - name: 'libacct'
    groups: 'wheel'
    pubkey: 'ssh-rsa AAAAB3NzaC1yc2EAAAABJQAAAQEAtkaGGkonm3HJmRoupKgM0A04uZu3aPhFyWmyMWCHTk1TtDskTgO0krOgUKuxAB2G/d39Xz6oISL9+dQdZt5aEJK7WoHpkK8l8xXfrIJ8OiWuJ+IRygjjLsib8tVTRsEIvMrQUtnhGzVNM7lQNXaEviGmR+ZunH68fv/QpomR5qW/veLFsR0KQLnd8yoG2+Tm8EdYouDcUPTS1nr9XdPSWGcsvpDq48JdxSmtXXC/8NHfdhpmCMmoC/IXbFl7typeLd9gt7EFvqOLWEbysEF3hD6hMAV3MEWaDnhf25n2cUgdAvdk086REgg2bXx1dBdeSi+wq5MadfP80UuPuaN2lw== libacct@ou.edu'

ssh_brokers:
  - alias: 'localhost'
    ip: '127.0.0.1'
    dn_suffix: 'localdomain'

# root db password
mariadb_root_pass: 'root'

# Passing the local domain on to apache
httpd_dn_suffix: "vagrant.localdomain"

# Local APC credentials
apc_username: apcuser
apc_password: apcpass

# Front end
# nginx_star_sites: [] # Use this if you have no star sites
nginx_star_sites:
 - name: journals.vagrant.localdomain
   upstreams:
     - name: journals-vagrant-localdomain
       servers:
         - ojs.vagrant.localdomain:443
   robots: disallow
# nginx_literal_sites: [] # Use this if you have no literal sites
nginx_literal_sites: []


# Credentials for creating the OJS DB
ojs_mariadb_login_username: root
ojs_mariadb_login_password: "{{ mariadb_root_pass }}"

# DB Client config
ojs_mariadb_host: localhost
ojs_mariadb_port: 3306
#ojs_mariadb_username:
ojs_mariadb_password: "{{ ojs_mariadb_username }}"
