---
syslogng_client_ip: 192.168.96.12
syslogng_dn_prefix: "syslog"
syslogng_dn_suffix: "vagrant.localdomain"
syslogng_client_prefix: "monitor"
syslogng_client_suffix: "vagrant.localdomain"
syslogng_client_cert: 
