---
# Configure a common baseline for all hosts
- hosts: vagrant
  become: true
  roles:
    - role: OULibraries.centos7
      tags: centos7
  pre_tasks:
    - include: pretasks.yml
      tags: pretasks

# Nothing specifically gets configured in this generic host. If it
# did, that would go here.
#
- hosts: monitor.vagrant.localdomain
  become: true
  roles:
    - role: OULibraries.apache2
      tags: apache2
    - role: OULibraries.mariadb
      tags: mariadb
    - role: OULibraries.zabbix
      tags: zabbix
 
- hosts: syslog.vagrant.localdomain
  become: true
  roles:
    - role: OULibraries.java
      tags: java
    - role: OULibraries.syslogng
      tags: syslog-ng
    - role: OULibraries.filebeat
      tags: filebeat
    - role: OULibraries.logstash
      tags: logstash

- hosts: elasticsearch.vagrant.localdomain
  become: true
  roles: 
    - role: OULibraries.java
      tags: java
    - role: OULibraries.elasticsearch
      tags: elasticsearch
    - role: OULibraries.kibana
      tags: kibana 


# Got back and configure interactive users and devel settings for all hosts
#- hosts: vagrant
#  become: true
#  roles:
#    - role: OULibraries.users
#      tags: users
