---
cas_services:
  - file: "starNgrok"
    serviceId: '^https://.*{{ my_httpd_dn_suffix }}/.*'
    name: "OULibraries ngrok"
    id: "1"
    evaluationOrder: "1"
    description: "OU Libraries ngrok"
    logoutUrl: "https://.*{{ my_httpd_dn_suffix }}/caslogout"
    logoutType: "NONE"


# Unique ID for CAS node
cas_host_name: cas.vagrant.localdomain

# Specify a cas overlay
cas_overlay_repo: "https://github.com/OULibraries/cas-overlay.git"
cas_overlay_version: "4.1-oulib"

# CAS login screen verbiage variables
cas_screen_welcome_instructions: "Login with your OUNetID (4x4)"
cas_screen_welcome_security:

cas_screen_label_netid: "<span class=\"accesskey\">O</span>UNetID (4x4):"
cas_authenticationFailure_AccountNotFoundException: "Sorry, unrecognized
username or password. Visit the <a href=\"https://libraries.ou
.edu/login-help\">Login Help</a> page for assistance."
